language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/acsone/bank-statement-reconcile ${HOME}/account-financial-tools -b 7.0-improve-acc-number-completion
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install xlrd pycoda

script:
  - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
